version: '3.8'

## Este arquivo é apenas para teste ## 

services:
  node1:
    image: pbl3
    environment:
        - NODEID=1
    volumes:
      - .:/app
    tty: true
    networks:
      minha_rede:
        ipv4_address: 172.16.103.6
  
  node2:
    image: pbl3
    environment:
        - NODEID=2
    volumes:
      - .:/app
    tty: true
    networks:
      minha_rede:
        ipv4_address: 172.16.103.7

  node3:
    image: pbl3
    environment:
        - NODEID=3
    volumes:
      - .:/app
    tty: true
    networks:
      minha_rede:
        ipv4_address: 172.16.103.4

networks:
  minha_rede:
    ipam:
      driver: default
      config:
        - subnet: 172.16.103.0/24