version: '3.8'

## Este arquivo é apenas para teste ## 


services:
  node1:
    image: pbl3
    # ports:
    #   - "7798:7798"
    environment:
        - NODEID=1
    #   - ADDRESNODES=['172.16.103.7', '172.16.103.11', '172.16.103.4']
    volumes:
      - .:/app
    tty: true
    networks:
      minha_rede:
        ipv4_address: 172.16.103.11
  
  node2:
    image: pbl3
    # ports:
    #   - "7798:7798"
    environment:
        - NODEID=2
    #   - ADDRESNODES=['172.16.103.7', '172.16.103.11', '172.16.103.4']
    volumes:
      - .:/app
    tty: true
    networks:
      minha_rede:
        ipv4_address: 172.16.103.7

  node3:
    image: pbl3
    # ports:
    #   - "7798:7798"
    environment:
        - NODEID=3
    #   - ADDRESNODES='{1: 172.16.103.7, 2: 172.16.103.11, 3: 172.16.103.4}'
    volumes:
      - .:/app
    tty: true
    networks:
      minha_rede:
        ipv4_address: 172.16.103.4

networks:
  minha_rede:
    ipam:
      driver: default
      config:
        - subnet: 172.16.103.0/24